### PR TITLE
Added gherkin auto-complete plugin

### PR DESCRIPTION
**Pull request by bubenkoff**
As there are opinions that auto-completion feature should go into this plugin, I've prepared a pull request merging it.
https://github.com/wbond/package_control_channel/pull/3989

### CODE REVIEW

**Comment by drewda** [comment]
Hello, I'm glad to merge this in. But before I do so, I'd like to double check to see if @AndyHitchman has a strong opinion either way.

**Comment by AndyHitchman** [comment]
The AndyHitchman/sublime-gherkin-autocomplete plugin has been accepted into package control directly (wbond/package_control_channel/pull/3989). So merging it here would probably cause confusion or conflicts?

**Comment by bubenkoff** [comment]
It's the same situation as with Sublime-Text-Table-Cleaner, no difference
and i don't think it will be a problem - nobody needs 2 plugins installed at the same time (sublime-gherkin-auto-complete and cucumber-sublime-bundle), so it's safe to merge

**Comment by drewda** [comment]
Your call, @AndyHitchman

**Comment by AndyHitchman** [comment]
Ok. No objections from me. Let's merge. I suggest we mention that both are not required.

**Comment by bubenkoff** [comment]
@AndyHitchman I added that to the readme

**Comment by bubenkoff** [comment]
@drewda so @AndyHitchman confirmed :)

**Comment by bubenkoff** [comment]
Hi
any change to get this merged?
btw: if you're not too interested in maintaining this package you can add me as contributor :)

**Comment by drewda** [comment]
Thanks for letting us bring in your code, @AndyHitchman 

And thanks for your patience, @bubenkoff. Sure, I'd appreciate your help maintaining this project. I'll add you as a committer. Please make all your changes in PRs (rather than direct commits to master).

**Comment by bubenkoff** [comment]
thanks!
sure, i'll do it properly

On 27 January 2015 at 23:26, Drew Dara-Abrams <notifications@github.com>
wrote:

> Thanks for letting us bring in your code, @AndyHitchman
> <https://github.com/AndyHitchman>
>
> And thanks for your patience, @bubenkoff <https://github.com/bubenkoff>.
> Sure, I'd appreciate your help maintaining this project. I'll add you as a
> committer. Please make all your changes in PRs (rather than direct commits
> to master).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drewda/cucumber-sublime-bundle/pull/16#issuecomment-71741330>
> .
>



-- 
Anatoly Bubenkov

**Comment by drewda** [comment]
Nice work, @bubenkoff. Thanks for jumping into this repo with all your energy.

**Pull request merged**
